name: Docker Image CI main 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubbuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: randomguy090
          password: ${{ secrets.DOCKER_SECRET }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64, linux/arm/v7
          push: true
          tags: randomguy090/tellobeep:latest
