name: Docker Image CI

on:
  push:
    branches: [ "main", "develop", "Docker_integration" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Build the Docker image
        uses: actions/checkout@v3
        run: docker build --build-arg user=admin --build-arg password=password --tag tellobeep .
      
      -
        name: show built images
        uses: actions/checkout@v1
        run: docker images
      -
        name: show secret
        env: 
          secret: ${{ secrets.TEST_SECRET}}
        run: |
          echo $secret
        
    
