name: Docker Image CI


on:
  push:
    branches: [ "main", "master"]
  pull_request:
    branches: [ "main", "master"]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: get repo
        uses: actions/checkout@v3.1.0
        with:
          repository: spottedmi/TelloBeep
          ref: Docker_integration
      -
        name: change dir
        run: cd TelloBeep && tree -a
      -
        name: cd
        run: cd TelloBeep && tree -a
        
      -
        name: print git
        run: git log
      -
        name: change branch
        run: git checkout Docker_integration
      -
        name: tree
        run: tree
      -
        name: Build the Docker image
        run:  docker build --build-arg user=admin --build-arg password=password --tag tellobeep .
      
      -
        name: show built images
        run: docker images
      -
        name: show secret
        env: 
          secret: ${{ secrets.DOCKER_SECRET}}
        run: |
          echo $secret
          
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: randomguy090
          password: ${{ secrets.DOCKER_SECRET }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: user/app:latest
